-- ============================================================================
-- Velare - pgcrypto auth helpers
-- Run this in the Supabase SQL Editor (one time, or whenever you change it).
--
-- DESIGN NOTE
-- -----------
-- The web app (Python) uses the `bcrypt` library to hash every password
-- BEFORE writing it to users.password. The stored value looks like:
--
--     $2b$12$abc...   (60 chars total)
--
-- That format is fully compatible with Postgres' pgcrypto `crypt()` function,
-- so the mobile app can use these RPCs to do equivalent work server-side:
--
--   * verify_user_password               → uses crypt(plain, hash) = hash.
--                                          Works on hashes generated by
--                                          either the web (Python bcrypt) or
--                                          this app (pgcrypto crypt+gen_salt).
--   * create_user_with_hashed_password   → bcrypts the password with
--                                          gen_salt('bf', 12) and inserts.
--                                          12 rounds matches the web (
--                                          _BCRYPT_ROUNDS = 12 in
--                                          utils/password_utils.py).
--   * reset_password_with_token          → re-bcrypts, clears the token.
--
-- Legacy fallback: verify_user_password also accepts a direct equality match
-- so any plain-text rows still in the DB (the web upgrades these on first
-- successful login) can still log in via the app.
-- ============================================================================

-- 1. Make sure pgcrypto is enabled.
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================================
-- 2. verify_user_password(email, password) -> boolean
-- ============================================================================
CREATE OR REPLACE FUNCTION public.verify_user_password(
    p_email    text,
    p_password text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_stored_hash text;
    v_normalized  text;
BEGIN
    SELECT password
      INTO v_stored_hash
      FROM users
     WHERE lower(email) = lower(trim(p_email))
     LIMIT 1;

    IF v_stored_hash IS NULL THEN
        RETURN FALSE;
    END IF;

    -- Bcrypt hash path. Web uses Python bcrypt which emits "$2b$"; pgcrypto
    -- only understands "$2a$". The two prefixes describe the same algorithm
    -- (the variant byte was just bumped to fix a separate bug in PHP), so we
    -- normalize "$2b$" / "$2y$" to "$2a$" before passing to crypt(). The
    -- resulting comparison is on the normalized form, so it works regardless
    -- of whether the row was written by the web or the app.
    IF v_stored_hash LIKE '$2_$%' AND length(v_stored_hash) = 60 THEN
        v_normalized := regexp_replace(v_stored_hash, '^\$2[by]\$', '$2a$');
        RETURN crypt(p_password, v_normalized) = v_normalized;
    END IF;

    -- Legacy plain-text path (the web auto-upgrades these on first login).
    RETURN v_stored_hash = p_password;
END;
$$;

GRANT EXECUTE ON FUNCTION public.verify_user_password(text, text)
    TO anon, authenticated;


-- ============================================================================
-- 3. create_user_with_hashed_password(email, password, user_type, status)
--    -> bigint (the new user_id, or NULL if email is already taken)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.create_user_with_hashed_password(
    p_email     text,
    p_password  text,
    p_user_type text,
    p_status    text DEFAULT 'pending'
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_email   text := lower(trim(p_email));
    v_user_id bigint;
BEGIN
    IF EXISTS (SELECT 1 FROM users WHERE lower(email) = v_email) THEN
        RETURN NULL;
    END IF;

    -- user_type is the custom enum `user_role`. status is varchar.
    -- Cast user_type explicitly so Postgres accepts the text parameter.
    INSERT INTO users (email, password, user_type, status, created_at)
    VALUES (
        v_email,
        crypt(p_password, gen_salt('bf', 12)),  -- 12 rounds, matches web
        p_user_type::user_role,
        COALESCE(p_status, 'pending'),
        NOW()
    )
    RETURNING user_id INTO v_user_id;

    RETURN v_user_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_user_with_hashed_password(text, text, text, text)
    TO anon, authenticated;


-- ============================================================================
-- 4. reset_password_with_token(email, new_password) -> boolean
-- ============================================================================
CREATE OR REPLACE FUNCTION public.reset_password_with_token(
    p_email        text,
    p_new_password text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_email text := lower(trim(p_email));
    v_rows  int;
BEGIN
    UPDATE users
       SET password = crypt(p_new_password, gen_salt('bf', 12)),
           reset_token = NULL,
           reset_token_expiry = NULL
     WHERE lower(email) = v_email;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN v_rows > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION public.reset_password_with_token(text, text)
    TO anon, authenticated;
